file manager
dariatopchii/domashki-dotnet-2022-topchii-daria pull request #1
Opened 2022-01-03 09:07 UTC by dariatopchii

2022-01-04 20:44 UTC, Gribok4E requested changes
В целом, очень хорошо, мелкие недочеты исправить и будет супер

2022-01-04 20:44 UTC, Gribok4E commented on dotnet 2022 study/Program.cs
> +                        break;
Нужно всегда юзать фигурные скобки в if

2022-01-04 20:44 UTC, Gribok4E commented on dotnet 2022 study/FileManager.cs
> +    }
А почему везде статика?)

2022-01-04 20:44 UTC, Gribok4E commented on dotnet 2022 study/FileManager.cs
> +
Здесь нужен ток один отступ

2022-01-04 20:44 UTC, Gribok4E commented on dotnet 2022 study/FileManager.cs
> +            using (StreamReader sr = File.OpenText(filepath))
Перед using нужен отступ

2022-01-04 20:44 UTC, Gribok4E commented on dotnet 2022 study/FileManager.cs
> +                for (int x = 0; x < lines.Length - 1; x++)
перед for нужен отступ

2022-01-09 15:55 UTC, dariatopchii commented on dotnet 2022 study/FileManager.cs
> +                for (int x = 0; x < lines.Length - 1; x++)
добавила

2022-01-09 15:55 UTC, dariatopchii commented on dotnet 2022 study/FileManager.cs
> +            using (StreamReader sr = File.OpenText(filepath))
добавила

2022-01-09 15:55 UTC, dariatopchii commented on dotnet 2022 study/FileManager.cs
> +
убрала

2022-01-09 15:56 UTC, dariatopchii commented on dotnet 2022 study/FileManager.cs
> +    }
поменяла))

2022-01-09 15:56 UTC, dariatopchii commented on dotnet 2022 study/Program.cs
> +                        break;
добавила

2022-01-13 09:26 UTC, merged